# Generated by Django 2.2 on 2019-03-13 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project2App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newusermodel',
            name='userForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relatedcontentmodel',
            name='relatedForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project2App.WikiModel'),
        ),
        migrations.AddField(
            model_name='wikimodel',
            name='wikiForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project2App.NewUserModel'),
        ),
    ]
