# Generated by Django 2.2 on 2019-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0002_auto_20190313_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedcontentmodel',
            name='image',
            field=models.ImageField(default='site_media/None/no-img.jpg', upload_to='site_media/'),
        ),
        migrations.AddField(
            model_name='wikimodel',
            name='image',
            field=models.ImageField(default='site_media/None/no-img.jpg', upload_to='site_media/'),
        ),
        migrations.AlterField(
            model_name='newusermodel',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
