# Generated by Django 2.2 on 2019-03-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0004_auto_20190314_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimodel',
            name='image',
            field=models.ImageField(blank=True, default='site_media/None/no-img.jpg', null=True, upload_to='site_media'),
        ),
    ]
