# Generated by Django 2.2 on 2019-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0005_auto_20190314_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimodel',
            name='image',
            field=models.ImageField(blank=True, default='site_media/None/no-img.jpg', null=True, upload_to='site_media/'),
        ),
    ]
