# Generated by Django 2.2 on 2019-03-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0006_auto_20190314_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimodel',
            name='image',
            field=models.ImageField(blank=True, default='site_media/None/no-img.jpg', null=True, upload_to='media/'),
        ),
    ]
