# Generated by Django 2.2 on 2019-03-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0007_auto_20190314_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
