# Generated by Django 2.2 on 2019-03-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0008_auto_20190314_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedcontentmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
