# Generated by Django 2.2 on 2019-03-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0009_auto_20190314_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedcontentmodel',
            old_name='Title',
            new_name='title',
        ),
    ]
