# Generated by Django 2.2 on 2019-07-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0010_auto_20190315_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimodel',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media'),
        ),
    ]
